# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meet.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Meet(object):
    def setupUi(self, Meet):
        Meet.setObjectName("Meet")
        Meet.resize(327, 277)
        self.centralwidget = QtWidgets.QWidget(Meet)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(12, 181, 103, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(121, 181, 74, 17))
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(11, 161, 51, 16))
        self.label_3.setObjectName("label_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(200, 180, 102, 17))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 11, 30, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(11, 30, 133, 50))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(11, 86, 37, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(11, 105, 133, 50))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(107, 205, 75, 23))
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        Meet.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Meet)
        self.statusbar.setObjectName("statusbar")
        Meet.setStatusBar(self.statusbar)

        self.retranslateUi(Meet)
        QtCore.QMetaObject.connectSlotsByName(Meet)

    def retranslateUi(self, Meet):
        _translate = QtCore.QCoreApplication.translate
        Meet.setWindowTitle(_translate("Meet", "MainWindow"))
        self.radioButton.setText(_translate("Meet", "Преподаватель"))
        self.radioButton_2.setText(_translate("Meet", "Учащийся"))
        self.label_3.setText(_translate("Meet", "Войти как"))
        self.radioButton_3.setText(_translate("Meet", "Администратор"))
        self.label.setText(_translate("Meet", "Логин"))
        self.lineEdit.setText(_translate("Meet", "0"))
        self.lineEdit.setPlaceholderText(_translate("Meet", "Логин"))
        self.label_2.setText(_translate("Meet", "Пароль"))
        self.lineEdit_2.setText(_translate("Meet", "0"))
        self.lineEdit_2.setPlaceholderText(_translate("Meet", "Пароль"))
        self.pushButton.setText(_translate("Meet", "Вход"))
